In [75]:
import pandas as pd
import numpy as np

def process_event_log_dataframe(df):
    df['Year'] = pd.to_datetime(df['Year'], format='%Y')
    df['Day'] = df['Day'] - 1
    df['Day'] = pd.to_timedelta(df['Day'], 'D')
    df['Hour'] = pd.to_timedelta(df['Hour'], 'h')
    df['Minute'] = pd.to_timedelta(df['Minute'], 'm')
    df['Second'] = pd.to_timedelta(df['Second'], 'S')
    df['Date'] = df['Year'] + df['Day'] + df['Hour'] + df['Minute'] + df['Second']
    df = df.drop(['Year', 'Day', 'Hour', 'Minute', 'Second', 'Zone', 'Type', 'Info'], axis=1)
    # reverse, since originally they are later first and earlier last
    df = df.iloc[::-1]
    df = df.reset_index(drop=True)
    return df


def split_event_dataframe_into_event_types(df):
    event_types = df['TypeText'].unique()
    event_dfs = {}
    for event_type in event_types:
        event_dfs[event_type] = df[df['TypeText'] == event_type].reset_index(drop=True)
    return event_dfs

In [14]:
df = pd.read_csv('data/EventLogData-WarbyParker.csv')
df = process_event_log_dataframe(df)

In [15]:
df

    TypeText                    Date
0      start 2021-07-03 15:54:21.960
1       exit 2021-07-03 15:54:41.050
2       exit 2021-07-03 15:54:41.520
3   entrance 2021-07-03 15:55:35.270
4   entrance 2021-07-03 15:55:37.160
5   entrance 2021-07-03 15:55:40.060
6   entrance 2021-07-03 15:55:47.020
7   entrance 2021-07-03 15:55:47.310
8   entrance 2021-07-03 15:56:54.210
9       exit 2021-07-03 15:58:15.810
10      exit 2021-07-03 15:58:57.680
11      exit 2021-07-03 15:58:58.180
12  entrance 2021-07-03 15:59:33.140
13  entrance 2021-07-03 15:59:33.600
14      exit 2021-07-03 15:59:36.610
15      exit 2021-07-03 15:59:37.250
16      exit 2021-07-03 15:59:38.950
17      exit 2021-07-03 16:02:39.350
18      exit 2021-07-03 16:03:09.820
19      exit 2021-07-03 16:03:10.710
20      exit 2021-07-03 16:03:38.930
21      exit 2021-07-03 16:03:41.510
22  entrance 2021-07-03 16:04:05.900
23  entrance 2021-07-03 16:04:16.120
24  entrance 2021-07-03 16:04:18.610
25  entrance 2021-07-03 16:04:19.310
26  entrance 2021-07-03 16:04:22.500
27  entrance 2021-07-03 16:06:17.320
28  entrance 2021-07-03 16:06:19.040
29  entrance 2021-07-03 16:06:19.490
30  entrance 2021-07-03 16:07:35.830
31  entrance 2021-07-03 16:07:36.360
32      exit 2021-07-03 16:07:40.250
33      exit 2021-07-03 16:07:40.770
34      exit 2021-07-03 16:07:41.270
35      exit 2021-07-03 16:08:09.300
36      exit 2021-07-03 16:08:09.800
37      exit 2021-07-03 16:08:10.420
38  entrance 2021-07-03 16:08:15.040
39  entrance 2021-07-03 16:08:18.020
40  entrance 2021-07-03 16:08:18.550
41      exit 2021-07-03 16:09:26.910
42  entrance 2021-07-03 16:09:48.970
43      exit 2021-07-03 16:10:02.760
44      exit 2021-07-03 16:10:09.720
45      exit 2021-07-03 16:10:15.770
46      exit 2021-07-03 16:10:16.670
47      exit 2021-07-03 16:11:22.040
48  entrance 2021-07-03 16:11:27.390
49  entrance 2021-07-03 16:11:28.100
50      exit 2021-07-03 16:11:37.420
51  entrance 2021-07-03 16:12:40.610
52      stop 2021-07-03 16:13:02.300

In [20]:
dfs = split_event_dataframe_into_event_types(df)

In [82]:
start_time = dfs['start']['Date'][0]
stop_time = dfs['stop']['Date'][0]
start_n_people = 9
n_integral = start_n_people * (stop_time - start_time) + (stop_time - dfs['entrance']['Date']).sum() - (stop_time - dfs['exit']['Date']).sum()
alpha = 0.7
n_entrances = len(dfs['entrance'])
n_exits = len(dfs['exit'])
est_mean_time = n_integral / (alpha * n_exits + (1 - alpha) * n_entrances)
est_mean_time

Timedelta('0 days 00:06:51.529182879')

In [79]:
(dfs['entrance']['Date'].iloc[1:].to_numpy() - dfs['entrance']['Date'].iloc[:-1].to_numpy()) / np.timedelta64(1, 's')

array([  1.89,   2.9 ,   6.96,   0.29,  66.9 , 158.93,   0.46, 272.3 ,
        10.22,   2.49,   0.7 ,   3.19, 114.82,   1.72,   0.45,  76.34,
         0.53,  38.68,   2.98,   0.53,  90.42,  98.42,   0.71,  72.51])

In [92]:
n_entrances / ((stop_time - start_time)/np.timedelta64(1, 'm')) * (6+51.529/60)

9.183127443454666

In [93]:
start_n_people * (stop_time - start_time) / (alpha * n_exits + (1 - alpha) * n_entrances)

Timedelta('0 days 00:06:32.336964980')